CREATE TABLE `order` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `tenant_id` int(10) NOT NULL COMMENT '租户id',
  `buyer_id` bigint(19) NOT NULL COMMENT '买家id',
  `buyer_name` varchar(64) NOT NULL DEFAULT '' COMMENT '买家姓名',
  `shop_name` varchar(64) DEFAULT NULL COMMENT '卖家姓名',
  `shop_id` bigint(20) NOT NULL COMMENT '卖家id',
  `pay_status` varchar(64) NOT NULL COMMENT '支付状态',
  `delivery_status` varchar(64) NOT NULL COMMENT '配送状态',
  `receive_status` varchar(64) NOT NULL COMMENT '签收状态',
  `reverse_status` varchar(64) NOT NULL COMMENT '售后状态',
  `pay_at` datetime DEFAULT NULL COMMENT '支付完成时间',
  `shipping_at` datetime DEFAULT NULL COMMENT '发货时间',
  `confirm_at` datetime DEFAULT NULL COMMENT '确认收货时间',
  `paid_amount` bigint(20) NOT NULL COMMENT '实际支付金额',
  `sku_origin_total_amount` bigint(20) NOT NULL COMMENT '商品总额',
  `sku_discount_total_amount` bigint(20) NOT NULL COMMENT '商品优惠总额',
  `ship_fee_origin_amount` bigint(20) NOT NULL COMMENT '运费总额',
  `ship_fee_discount_total_amount` bigint(20) NOT NULL COMMENT '运费优惠总额',
  `delivery_address` varchar(2048) DEFAULT NULL COMMENT '收货地址',
  `deleted` int(10) NOT NULL COMMENT '逻辑删除',
  `create_by` varchar(64) DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `accomplish_at` datetime DEFAULT NULL COMMENT '订单完成时间',
  `version` int(10) NOT NULL DEFAULT '0' COMMENT '版本号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_order_buyer_id` (`buyer_id`),
  KEY `idx_order_shop_id` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单';


CREATE TABLE `order_line` (
  `id` bigint(20) NOT NULL COMMENT '订单行id',
  `tenant_id` int(10) DEFAULT NULL COMMENT '租户id',
  `order_id` bigint(20) NOT NULL COMMENT '店铺订单id',
  `pay_status` varchar(64) NOT NULL COMMENT '支付状态',
  `delivery_status` varchar(64) NOT NULL COMMENT '配送状态',
  `receive_status` varchar(64) NOT NULL COMMENT '签收状态',
  `reverse_status` varchar(64) NOT NULL COMMENT '售后状态',
  `refund_at` datetime DEFAULT NULL COMMENT '退款完成时间',
  `confirm_at` datetime DEFAULT NULL COMMENT '确认收获时间',
  `sku_id` bigint(19) DEFAULT NULL COMMENT 'sku id',
  `sku_code` varchar(64) DEFAULT NULL COMMENT 'sku code',
  `sku_name` varchar(512) NOT NULL DEFAULT '' COMMENT 'sku 名称',
  `quantity` int(10) NOT NULL COMMENT '数量',
  `paid_amount` bigint(20) NOT NULL COMMENT '实际支付金额',
  `sku_origin_total_amount` bigint(20) NOT NULL COMMENT '商品总额',
  `sku_discount_total_amount` bigint(20) NOT NULL COMMENT '商品优惠总额',
  `ship_fee_origin_amount` bigint(20) NOT NULL COMMENT '运费总额',
  `ship_fee_discount_total_amount` bigint(20) NOT NULL COMMENT '运费优惠总额',
  `deleted` int(10) NOT NULL COMMENT '逻辑删除',
  `create_by` varchar(64) DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `item_id` bigint(20) NOT NULL COMMENT '商品id',
  `item_name` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `version` int(10) NOT NULL DEFAULT '0' COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_order_line_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单行';