version: '3'

services:
  mysql:
    image: mysql:5.7.16
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD:-password}'
    expose:
      - 3306
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    restart: always
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
      - 9300:9300
  canal: 
    image: canal/canal-server:v1.1.4
    container_name: canal-server
    restart: always
    ports: 
      - 11111:11111
    environment: 
      - canal.instance.mysql.slaveId=12
      - canal.auto.scan=false
      - canal.destinations=example
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=password
    depends_on:
      - mysql  
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    restart: always
    expose:
      - '2181'
    ports:
      - '${ZK_PORT:-2181}:2181' 

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.100.53 #192.168.1.105 #192.168.100.53 #按自己的ip地址改
    volumes:
      - ./kafka-logs:/kafka
    depends_on:
      - zookeeper    
    
  #nacos:
  #  image: nacos/nacos-server:latest
  #  container_name: nacos
  #  restart: on-failure
  #  expose:
  #    - '8848'
  #  environment:
  #    MODE: standalone
  #  ports:
  #    - '${NACOS_PORT:-8848}:8848'
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   expose:
  #     - '6379'
  #   ports:
  #     - '${REDIS_PORT:-6379}:6379'